import nodemailer from 'nodemailer';

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { to, subject, body, strategy, price, signal } = req.body;

  try {
    // Create Gmail transporter
    const transporter = nodemailer.createTransporter({
      service: 'gmail',
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    // Email template
    const htmlBody = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #2c3e50;">🚨 Trading Signal Alert</h2>
        <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h3 style="color: ${
            signal === 1 ? '#28a745' : '#dc3545'
          }; margin-top: 0;">
            ${signal === 1 ? '📈 BUY SIGNAL' : '📉 SELL SIGNAL'}
          </h3>
          <p><strong>Strategy:</strong> ${strategy}</p>
          <p><strong>Price:</strong> ${price} USD/EUR</p>
          <p><strong>Signal:</strong> ${signal === 1 ? 'BUY' : 'SELL'}</p>
          <p><strong>Time:</strong> ${new Date().toLocaleString()}</p>
        </div>
        <p style="color: #6c757d; font-size: 12px;">
          Generated by USD/EUR Trading Dashboard
        </p>
      </div>
    `;

    // Send email
    await transporter.sendMail({
      from: process.env.EMAIL_USER,
      to: to,
      subject: subject,
      html: htmlBody,
    });

    res.status(200).json({ success: true, message: 'Email sent successfully' });
  } catch (error) {
    console.error('Email error:', error);
    res
      .status(500)
      .json({ error: 'Failed to send email', details: error.message });
  }
}
